### ISSUE TITLE
Links in plugin descriptions should get `target="_blank"`

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/.github#24]
See https://github.com/craftcms/cms/discussions/10162.

**Comment by lindseydiloreto** [comment]
I see this is closed as "not planned"... any reason why? It seems like a good idea.

If a potential customer clicks on a link in the plugin description (ie: to the plugin's documentation), that link should **definitely** open in a new tab (IMO). Otherwise, you are steering people _away_ from the point of sale, and potentially causing confusion amongst people who wonder "how did I get to this random page?"
